name = "shortener"
main = "src/index.ts"
compatibility_date = "2025-09-01"

workers_dev = false
preview_urls = false

[observability]
enabled = true

  [observability.logs]
  head_sampling_rate = 1

  [observability.traces]
  enabled = true
  head_sampling_rate = 0.05

[[routes]]
pattern = "mart.fyi/*"
zone_name = "mart.fyi"

[[routes]]
pattern = "www.mart.fyi/*"
zone_name = "mart.fyi"

[vars]
API_USER_ID = "1"
DISABLE_REGISTRATION = "false"
ROOT_REDIRECT = ""
NOT_FOUND_BEHAVIOR = "redirect"
THEME = "darkly"

[[d1_databases]]
binding = "DB"
database_name = "shortener"
database_id = "f6539397-d3be-489f-8ab5-f5751fcd34ba"
migrations_dir = "migrations"
