"""Adding click tracking

Revision ID: 8a87d5239b60
Revises: e92788369ba9
Create Date: 2022-03-17 19:49:37.703971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a87d5239b60'
down_revision = 'e92788369ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortlinks', sa.Column('expired', sa.Boolean(), nullable=False, default=False))
    op.add_column('shortlinks', sa.Column('expiration_date', sa.DateTime(), nullable=True, default=None))
    op.add_column('shortlinks', sa.Column('max_clicks', sa.Integer(), nullable=False, default=-1))
    op.add_column('shortlinks', sa.Column('current_clicks', sa.Integer(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortlinks', 'current_clicks')
    op.drop_column('shortlinks', 'max_clicks')
    op.drop_column('shortlinks', 'expiration_date')
    op.drop_column('shortlinks', 'expired')
    # ### end Alembic commands ###
