"""Adding country name

Revision ID: eb281a02da0b
Revises: d6c01b84c43a
Create Date: 2022-04-04 16:54:04.276435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb281a02da0b'
down_revision = 'd6c01b84c43a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('country_name', sa.String(length=255), nullable=False, server_default='Unknown'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'country_name')
    # ### end Alembic commands ###
