"""Add deletion

Revision ID: ffc533128925
Revises: 1c079544ca62
Create Date: 2022-03-17 22:00:24.623751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc533128925'
down_revision = '1c079544ca62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortlinks', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortlinks', 'deleted')
    # ### end Alembic commands ###
